"""Added Car model

Revision ID: 8a84f5c37e63
Revises: 129aedc2b996
Create Date: 2022-07-13 19:48:51.093988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a84f5c37e63'
down_revision = '129aedc2b996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=25), nullable=True),
    sa.Column('model', sa.String(length=25), nullable=True),
    sa.Column('year', sa.String(length=25), nullable=True),
    sa.Column('color', sa.String(length=25), nullable=True),
    sa.Column('price', sa.String(length=25), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
