"""Incr pword contraint size

Revision ID: e76618b89518
Revises: 8a84f5c37e63
Create Date: 2022-07-15 21:05:27.601923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76618b89518'
down_revision = '8a84f5c37e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'make',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('car', 'model',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('car', 'year',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('car', 'color',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('car', 'price',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('car', 'price',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    op.alter_column('car', 'color',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    op.alter_column('car', 'year',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    op.alter_column('car', 'model',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    op.alter_column('car', 'make',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###
